bandas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [path('admin/', admin.site.urls), path('', include('portfolio.urls')), path('noobsite/', include('noobsite.urls')), path('pwsite/', include('pwsite.urls')), path('novaapp/', include('novaapp.urls')), path('AppBandas/', include('bands.urls')), path('BlogApp/', include('BlogApp.urls')),path('AppCurso/',include('curso.urls')),path('AppFestivais/', include('festivais.urls')), path('Autenticacao/', include('Autenticacao.urls')), path('meteo/', include('meteo.urls')), ]

bands/urls.py
from django.urls import path
from . import views

app_name = 'bands'
urlpatterns = [
    path('homePage', views.homePage_view, name = 'homePage'),
    path('', views.listBands_view, name = 'bandas'),
    path('banda/<str:band_name>', views.listAlbums_view, name = 'banda'),
    path('album/<str:album_name>', views.listMusics_view, name = 'album'),
    path('musica/<str:music_name>', views.musica_view, name = 'musica'),
    path('criarBanda/nova', views.nova_banda_view, name = 'nova_banda'),
    path('criarAlbum/novo/<str:band_name>', views.novo_album_view, name = 'novo_album'),
    path('criarMusica/nova/<str:album_name>', views.nova_musica_view, name = 'nova_musica'),
    path('editarBanda/<str:band_name>', views.edita_banda_view, name = 'edita_banda'),
    path('editarAlbum/<str:album_name>', views.edita_album_view, name = 'edita_album'),
    path('editarMusica/<str:musica_name>', views.edita_musica_view, name = 'edita_musica'),
    path('apagarBanda/<str:band_name>', views.apaga_banda_view, name = 'apaga_banda'),
    path('apagarAlbum/<str:album_name>', views.apaga_album_view, name = 'apaga_album'),
    path('apagarMusica/<str:musica_name>', views.apaga_musica_view, name = 'apaga_musica')
    ]

curso/urls.py
from django.urls import path
from . import views


app_name = 'cursos'
urlpatterns = [
    path('', views.listCursos_view, name = 'cursos'),
    path('cursos/<str:curso1_name>', views.listCurso_view, name = 'curso'),
    path('disciplina/<str:disciplina1_name>', views.listDisciplina_view, name = 'disciplina'),
    path('disciplina/projeto/<str:disciplina2_name>', views.listDisciplinaProjeto_view, name = 'projeto'),
    path('departamentos', views.listDepartamentos_view, name = 'departamentos'),
    path('departamento/<str:departamento_name>', views.listDepartamento_view, name = 'departamento'),
    path('areasCientificas', views.listAreasCientificas_view , name = 'areasCientificas'),
    path('areaCientifica/<str:areaCientifica_name>', views.listAreaCientifica_view, name = 'areaCientifica'),
    path('docentes', views.listDocentes_view, name = 'docentes'),
    path('docente/<str:docente_name>', views.listDocente_view, name = 'docente'),
    path('editaCurso/<str:curso_name>' , views.edita_curso_view, name = 'edita_curso'),
    path('novoCurso', views.novo_curso_view, name = 'novo_curso'),
    path('apagarCurso/<str:curso_name>' , views.apaga_curso_view, name = 'apaga_curso'),
    path('editaDisciplina/<str:disciplina_name>', views.edita_disciplina_view, name = 'edita_disciplina'),
    path('novaDisciplina', views.nova_disciplina_view, name = 'nova_disciplina'),
    path('apagarDisciplina/<str:disciplina_name>', views.apaga_disciplina_view, name = 'apaga_disciplina'),
    path('editaDepartamento/<str:departamento_name>' , views.edita_departamento_view, name = 'edita_departamento'),
    path('novoDepartamento', views.novo_Departamento_view, name = 'novo_departamento'),
    path('apagarDepartamento/<str:departamento_name>', views.apaga_departamento_view, name = 'apaga_departamento'),
    path('editaAreaCientifica/<str:area_cientifica_name>', views.edita_AreaCientifica_view, name = 'edita_areaCientifica'),
    path('novaAreaCientifica', views.nova_AreaCientifica_view, name = 'nova_areaCientifica'),
    path('apagarAreaCientifica/<str:area_cientifica_name>', views.apaga_AreaCientifica_view, name ='apaga_areaCientifica'),
    path('editaDocente/<str:docente_name>', views.edita_Docente_view,  name = 'edita_docente'),
    path('novoDocente', views.novo_Docente_view, name = 'novo_docente'),
    path('apagarDocente/<str:docente_name>', views.apaga_Docente_view, name = 'apaga_docente'),
    path('editaProjeto/<str:disciplina_name>', views.edita_Projeto_view, name = 'edita_projeto'),
    path('novoProjeto', views.novo_Projeto_view, name = 'novo_projeto'),
    path('apagaProjeto/<str:disciplina_name>', views.apaga_Projeto_view, name = 'apaga_projeto'),
    ]

curso/models.py
from django.db import models


class Departamento (models.Model):
    nome = models.CharField(max_length = 50)

    def __str__(self):
        return self.nome

class AreaCientifica (models.Model):
    nome = models.CharField(max_length = 50)

    def __str__(self):
        return self.nome

class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length = 50)

    def __str__(self):
        return self.nome

class Docente(models.Model):
    nome = models.CharField(max_length = 50)

    def __str__(self):
        return self.nome

class Disciplina (models.Model):
    nome = models.CharField(max_length = 50)
    areaCientifica = models.ForeignKey(AreaCientifica, on_delete = models.CASCADE, related_name = 'Disciplina')
    ano = models.IntegerField()
    semestre = models.CharField(max_length = 50)
    ects = models.IntegerField()
    curricularUnitReadableCode = models.CharField(max_length = 50)
    docentes = models.ManyToManyField(Docente, related_name = 'Disciplinas', blank=True, null=True)
    linguagensProgramacao = models.ManyToManyField(LinguagemProgramacao , related_name = 'Disciplinas', blank=True, null=True)


    def __str__(self):
        return self.nome

class Curso (models.Model):
    nome = models.CharField(max_length = 50)
    apresentacao = models.TextField()
    objectivos = models.TextField()
    competencias = models.TextField()
    departamento =  models.ForeignKey(Departamento, on_delete = models.CASCADE, related_name = 'Curso')
    condicoesAcesso = models.TextField()
    oportunidadesCarreira = models.TextField()
    disciplinas = models.ManyToManyField(Disciplina, related_name = 'Curso')
    imagem = models.ImageField(upload_to='app/fotos', null=True, blank=True)

    def __str__(self):
        return self.nome

class Projeto (models.Model):
    disciplina = models.OneToOneField(Disciplina, on_delete = models.CASCADE, related_name = 'Projeto')
    descricao = models.TextField()
    conceitosAplicados = models.TextField()
    tecnologiasUtilizadas = models.TextField()
    linguagensProgramacao = models.ManyToManyField(LinguagemProgramacao , related_name = 'Projetos')
    imagem = models.ImageField(null = True, blank = True)
    linkYoutube = models.URLField()
    linkGitHub = models.URLField()

curso/forms.py
from django import forms
from .models import *

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'

class DisciplinaForm(forms.ModelForm):
    class Meta:
        model = Disciplina
        fields = '__all__'

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = '__all__'

class AreaCientificaForm(forms.ModelForm):
    class Meta:
        model = AreaCientifica
        fields = '__all__'

class LinguagemProgramacaoForm(forms.ModelForm):
    class Meta:
        model = LinguagemProgramacao
        fields = '__all__'

class DocenteForm(forms.ModelForm):
    class Meta:
        model = Docente
        fields = '__all__'


class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'

curso/views.py
from django.shortcuts import render, redirect
from .models import Departamento, Curso, AreaCientifica, LinguagemProgramacao, Docente, Disciplina, Projeto
from .forms import CursoForm, DisciplinaForm, DepartamentoForm, AreaCientificaForm, LinguagemProgramacaoForm, DocenteForm, ProjetoForm


def novo_curso_view(request):
    form = CursoForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:cursos')
    context = {'form': form}

    return render(request, 'novoCurso.html', context)


def edita_curso_view(request, curso_name):
    curso = Curso.objects.get(nome = curso_name)

    if request.POST:
        form = CursoForm(request.POST or None, request.FILES, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('cursos:curso',  curso)
    else:
        form = CursoForm(instance=curso)  # cria formulário com dados da instância autor

    context = {'form': form, 'curso' : curso}
    return render(request, 'editaCurso.html', context)


def apaga_curso_view(request, curso_name):
    curso = Curso.objects.get(nome = curso_name)
    curso.delete()
    return redirect('cursos:cursos')


def nova_disciplina_view(request):

    form = DisciplinaForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:cursos')
    context = {'form': form}

    return render(request, 'novaDisciplina.html', context)

def edita_disciplina_view(request, disciplina_name):

    disciplina = Disciplina.objects.get(nome = disciplina_name)

    if request.POST:
        form = DisciplinaForm(request.POST or None, request.FILES, instance=disciplina)
        if form.is_valid():
            form.save()
            return redirect('cursos:disciplina',  disciplina)
    else:
        form = DisciplinaForm(instance=disciplina)  # cria formulário com dados da instância autor

    context = {'form': form, 'disciplina' : disciplina}
    return render(request, 'editaDisciplina.html', context)

def apaga_disciplina_view(request, disciplina_name):
    disciplina = Disciplina.objects.get(nome = disciplina_name)
    disciplina.delete()
    return redirect('cursos:cursos')



def novo_Departamento_view(request):
    form = DepartamentoForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:departamentos')
    context = {'form': form}

    return render(request, 'novoDepartamento.html', context)

def edita_departamento_view(request, departamento_name):
    departamento = Departamento.objects.get(nome = departamento_name)

    if request.POST :
        form = DepartamentoForm(request.POST or None, request.FILES, instance=departamento)
        if form.is_valid():
            form.save()
            return redirect('cursos:departamento', departamento)
    else:
        form = DepartamentoForm(instance=departamento)  # cria formulário com dados da instância autor

    context = {'form': form, 'departamento' : departamento}
    return render(request, 'editaDepartamento.html', context)

def apaga_departamento_view(request, departamento_name):
    departamento = Departamento.objects.get(nome = departamento_name)
    departamento.delete()
    return redirect('cursos:departamentos')

def nova_AreaCientifica_view(request):
    form = AreaCientificaForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:areasCientificas')
    context = {'form': form}

    return render(request, 'novaAreaCientifica.html', context)



def edita_AreaCientifica_view(request, area_cientifica_name):
    areaCientifica = AreaCientifica.objects.get(nome = area_cientifica_name)

    if request.POST :
        form = AreaCientificaForm(request.POST or None, request.FILES, instance=areaCientifica)
        if form.is_valid():
            form.save()
            return redirect('cursos:areaCientifica', areaCientifica)
    else:
        form = AreaCientificaForm(instance=areaCientifica)  # cria formulário com dados da instância autor

    context = {'form': form, 'areaCientifica' : areaCientifica}
    return render(request, 'editaAreaCientifica.html', context)

def apaga_AreaCientifica_view(request, area_cientifica_name):
    areaCientifica = AreaCientifica.objects.get(nome = area_cientifica_name)
    areaCientifica.delete()
    return redirect('cursos:areasCientificas')

def novo_Docente_view(request):
    form = DocenteForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:docentes')
    context = {'form': form}

    return render(request, 'novoDocente.html', context)

def edita_Docente_view(request, docente_name):
    docente = Docente.objects.get(nome = docente_name)

    if request.POST :
        form = DocenteForm(request.POST or None, request.FILES, instance=docente)
        if form.is_valid():
            form.save()
            return redirect('cursos:docente', docente)
    else:
        form = DocenteForm(instance=docente)  # cria formulário com dados da instância autor

    context = {'form': form, 'docente' : docente}
    return render(request, 'editaDocente.html', context)

def apaga_Docente_view(request, docente_name):
    docente = Docente.objects.get(nome = docente_name)
    docente.delete()
    return redirect('cursos:docentes')

def novo_Projeto_view(request):
    form = ProjetoForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:cursos')
    context = {'form': form}

    return render(request, 'novoProjeto.html', context)

def edita_Projeto_view(request, disciplina_name):
    disciplina = Disciplina.objects.get(nome = disciplina_name)
    projeto = Projeto.objects.get(disciplina__nome = disciplina_name)

    if request.POST :
        form = ProjetoForm(request.POST or None, request.FILES, instance=projeto)
        if form.is_valid():
            form.save()
            return redirect('cursos:projeto', disciplina)
    else:
        form = ProjetoForm(instance=projeto)  # cria formulário com dados da instância autor

    context = {'form': form, 'disciplina' : disciplina}
    return render(request, 'editaProjeto.html', context)


def apaga_Projeto_view(request, disciplina_name):
    projeto = Projeto.objects.get(disciplina__nome = disciplina_name)
    projeto.delete()
    return redirect('cursos:disciplina', disciplina_name)




def listCurso_view(request, curso1_name):
    context = {
        'curso' : Curso.objects.get(nome = curso1_name)

    }
    return render(request, 'listCurso.html', context)


def listDepartamentos_view(request):
    context = {
        'departamentos' : Departamento.objects.all()
    }
    return render(request, 'listDepartamentos.html', context)

def listAreasCientificas_view(request):
    context = {
        'areasCientificas' : AreaCientifica.objects.all()
    }
    return render(request, 'listAreasCientificas.html', context)

def listDocentes_view(request):
    context = {
        'docentes' : Docente.objects.all()
    }
    return render(request, 'listDocentes.html', context)

def listDocente_view(request, docente_name):
    context = {
        'docente' : Docente.objects.get(nome = docente_name)
    }
    return render(request, 'listDocente.html', context)

def listAreaCientifica_view(request,areaCientifica_name):
    context = {
        'areaCientifica' : AreaCientifica.objects.get(nome = areaCientifica_name)
    }
    return render(request, 'listAreaCientifica.html', context)


def listDepartamento_view(request, departamento_name):
    context = {
        'departamento' : Departamento.objects.get(nome = departamento_name)
    }
    return render(request, 'listDepartamento.html', context)

def listDisciplina_view(request, disciplina1_name):
    context = {
        'disciplina' : Disciplina.objects.get(nome = disciplina1_name),
        'projeto' : Projeto.objects.filter(disciplina__nome = disciplina1_name),
    }
    return render(request, 'listDisciplina.html', context)

def listDisciplinaProjeto_view(request, disciplina2_name):
    context = {
        'projeto' : Projeto.objects.get(disciplina__nome = disciplina2_name),
    }
    return render(request, 'listDisciplinaProjeto.html', context)

def listCursos_view(request):
    context = {
        'cursos' : Curso.objects.all()
    }

    return render(request, 'listCursos.html', context)

curso/templates/editaAreaCientifica.html
{% extends "layout3.html" %}

{% block content %}
    <h3>Edita Area Cientifica</h3>

    <form action="{% url 'cursos:edita_areaCientifica' areaCientifica.nome %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

curso/templates/editaDisciplina.html
{% extends "layout3.html" %}

{% block content %}
    <h3>Edita Disciplina</h3>

    <form action="{% url 'cursos:edita_disciplina' disciplina.nome %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

curso/templates/editaDocente.html
{% extends "layout3.html" %}

{% block content %}
    <h3>Edita Docente</h3>

    <form action="{% url 'cursos:edita_docente' docente.nome %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

curso/templates/layout3.html
<!DOCTYPE html>
<html>
<head>
 <meta charset = "UTF-8">
 {% load static %}
   <link rel="stylesheet" href="{% static 'cursos/estilos.css' %}">
 <title>Curso</title>
</head>
<body>

  <nav>
  <div class="wrapper">
    <div class="logo"><a href="https://a22202735.pythonanywhere.com/AppCurso/">AppCursos</a></div>
    <input type="radio" name="slider" id="menu-btn">
    <input type="radio" name="slider" id="close-btn">
    <ul class="nav-links">
      <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
      <li><a href="https://a22202735.pythonanywhere.com/AppCurso/departamentos">Departamentos</a></li>
      <li><a href="https://a22202735.pythonanywhere.com/AppCurso/areasCientificas">Áreas Científicas</a></li>
      <li><a href="https://a22202735.pythonanywhere.com/AppCurso/docentes">Docentes</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="https://a22202735.pythonanywhere.com/Autenticacao/logout/AppCurso">Logout</a></li>
        {% else %}
            <li> <a href= "https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso">Login</a></li>
        {% endif %}

        <li><a href="#">Contacto</a></li>

    </ul>
    <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
  </div>
</nav>

<div class="body-container">
    <div class="body-text">
</div>
</div>

     {% block content %}
     {% endblock %}


</body>
</html>

curso/templates/listAreaCientifica.html
{% extends "layout3.html" %}

{% block content %}

<div class = "cursoTeste">


<h1 class="titulo2">{{areaCientifica.nome}}</h1>


{% if request.user.is_authenticated %}
    <h1 class="titulo3"><a href="https://a22202735.pythonanywhere.com/AppCurso/apagarAreaCientifica/{{areaCientifica.nome}}"><span class = "green">Apaga</span></a> ou <a href="https://a22202735.pythonanywhere.com/AppCurso/editaAreaCientifica/{{areaCientifica.nome}}"><span class = "green">edita</span></a> esta Área Científica!</h1>
{% else %}
    <h1 class="titulo3"><a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/apagarAreaCientifica/{{areaCientifica.nome}}"><span class = "green">Apaga</span></a> ou <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/editaAreaCientifica/{{areaCientifica.nome}}"><span class = "green">edita</span></a> esta Área Científica!</h1>
{% endif %}


    </div>



{% endblock %}

curso/templates/listAreasCientificas.html
{% extends "layout3.html" %}

{% block content %}



    <div class = "cursoTeste">


<h1 class="titulo2">Areas Cientificas</h1>


{% if request.user.is_authenticated %}
    <h1 class="titulo3">Adiciona <a href="https://a22202735.pythonanywhere.com/AppCurso/novaAreaCientifica"><span class = "green">aqui</span></a> uma Área Científica!</h1>
{% else %}
     <h1 class="titulo3">Adiciona <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/novaAreaCientifica"><span class = "green">aqui</span></a> uma Área Científica!</h1>
{% endif %}



    {% for areaCientifica in areasCientificas %}
                <div class="article-box1">

                   <div class="info-content">
                       <ul>
                        <h4><a href= "https://a22202735.pythonanywhere.com/AppCurso/areaCientifica/{{areaCientifica.nome}}">{{areaCientifica.nome}}</a></h4>
                       </ul>
                   </div>

                </div>





    {% endfor %}




    </div>


{% endblock %}

curso/templates/listCurso.html
{% extends "layout3.html" %}

{% block content %}



        <div class = "cursoTeste">


<h1 class="titulo2">{{curso.nome}}</h1>


{% if request.user.is_authenticated %}
    <h1 class="titulo3"><a href="https://a22202735.pythonanywhere.com/AppCurso/apagarCurso/{{curso.nome}}"><span class = "green">Apaga</span></a> ou <a href="https://a22202735.pythonanywhere.com/AppCurso/editaCurso/{{curso.nome}}"><span class = "green">edita</span></a> este Curso!</h1>
{% else %}
    <h1 class="titulo3"><a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/apagarCurso/{{curso.nome}}"><span class = "green">Apaga</span></a> ou <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/editaCurso/{{curso.nome}}"><span class = "green">edita</span></a> este Curso!</h1>
{% endif %}




                <div class="article-box1">
                   <div class="info-content">
                       <ul>
                        <h4>Apresentação</h4>
                        <span class= "black">{{curso.apresentacao}}</span>
                        <h4>Objectivos</h4>
                        <span class= "black">{{curso.objectivos}}</span>
                        <h4>Competencias</h4>
                        <span class= "black">{{curso.competencias}}</span>
                        <h4>Condições de Acesso</h4>
                        <span class= "black">{{curso.condicoesAcesso}}</span>
                        <h4>Oportunidades de Carreira</h4>
                        <span class= "black">{{curso.oportunidadesCarreira}}</span>
                        <h4>Departamento</h4>
                        <span class= "black">{{curso.departamento.nome}}</span>
                       </ul>
                   </div>

                </div>



               <div class="article-box1">
                   <div class="info-content">
                       <ul>
                        <h4>Disciplinas</h4>
                        <h5>1 º Ano</h5>
                        <h6>1 º Semestre</h6>
                        {% for disciplina in curso.disciplinas.all %}
                             <ul>
                             {% if disciplina.semestre ==  "1º Semestre"  and disciplina.ano ==  1 %}
                                <a href= "{% url 'cursos:disciplina' disciplina.nome  %}">{{disciplina.nome}}</a>
                             {% endif %}
                             </ul>
                        {% endfor %}
                        <h6>2 º Semestre</h6>
                        {% for disciplina in curso.disciplinas.all %}
                             <ul>
                             {% if disciplina.semestre ==  "2º Semestre"  and disciplina.ano ==  1 %}
                                <a href= "{% url 'cursos:disciplina' disciplina.nome  %}">{{disciplina.nome}}</a>
                             {% endif %}
                             </ul>
                        {% endfor %}
                        <h5>2 º Ano</h5>
                        <h6>1 º Semestre</h6>
                        {% for disciplina in curso.disciplinas.all %}
                             <ul>
                             {% if disciplina.semestre ==  "1º Semestre"  and disciplina.ano ==  2 %}
                                <a href= "{% url 'cursos:disciplina' disciplina.nome  %}">{{disciplina.nome}}</a>
                             {% endif %}
                             </ul>
                        {% endfor %}
                        <h6>2 º Semestre</h6>
                        {% for disciplina in curso.disciplinas.all %}
                             <ul>
                             {% if disciplina.semestre ==  "2º Semestre"  and disciplina.ano ==  2 %}
                                <a href= "{% url 'cursos:disciplina' disciplina.nome  %}">{{disciplina.nome}}</a>
                             {% endif %}
                             </ul>
                        {% endfor %}
                        <h5>3 º Ano</h5>
                         <h6>1 º Semestre</h6>
                        {% for disciplina in curso.disciplinas.all %}
                             <ul>
                             {% if disciplina.semestre ==  "1º Semestre"  and disciplina.ano ==  3 %}
                                <a href= "{% url 'cursos:disciplina' disciplina.nome  %}">{{disciplina.nome}}</a>
                             {% endif %}
                             </ul>
                        {% endfor %}
                        <h6>2 º Semestre</h6>
                        {% for disciplina in curso.disciplinas.all %}
                             <ul>
                             {% if disciplina.semestre ==  "2º Semestre"  and disciplina.ano ==  3 %}
                                <a href= "{% url 'cursos:disciplina' disciplina.nome  %}">{{disciplina.nome}}</a>
                             {% endif %}
                             </ul>
                        {% endfor %}

                       </ul>
                   </div>

                </div>



    </div>






{% endblock %}

curso/templates/listCursos.html
{% extends "layout3.html" %}

{% block content %}


<div class = "cursoTeste">


<h1 class="titulo2">Cursos</h1>


{% if request.user.is_authenticated %}
    <h1 class="titulo3">Adiciona <a href="https://a22202735.pythonanywhere.com/AppCurso/novoCurso"><span class = "green">aqui</span></a> um curso!</h1>
{% else %}
     <h1 class="titulo3">Adiciona <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/novoCurso"><span class = "green">aqui</span></a> um curso!</h1>
{% endif %}







  {% for curso in cursos %}
                <div class="article-box1">

                   <div class="info-content">
                       <ul>
                        <h2>{{curso.departamento}}</h2>
                        <h3><a href="https://a22202735.pythonanywhere.com/AppCurso/cursos/{{curso.nome}}">{{curso.nome}}</a></h3>
                       </ul>
                   </div>
                       <img src="{{ curso.imagem.url }}" alt="{{ curso.nome }}">
                </div>







 {% endfor %}




    </div>

{% endblock %}

curso/templates/listDepartamento.html
{% extends "layout3.html" %}

{% block content %}


<div class = "cursoTeste">



<h1 class="titulo2">{{departamento.nome}}</h1>


{% if request.user.is_authenticated %}
    <h1 class="titulo3"><a href="https://a22202735.pythonanywhere.com/AppCurso/apagarDepartamento/{{departamento.nome}}"><span class = "green">Apaga</span></a> ou <a href="https://a22202735.pythonanywhere.com/AppCurso/editaDepartamento/{{departamento.nome}}"><span class = "green">edita</span></a> este Departamento!</h1>
{% else %}
    <h1 class="titulo3"><a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/apagarDepartamento/{{departamento.nome}}"><span class = "green">Apaga</span></a> ou <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/editaDepartamento/{{departamento.nome}}"><span class = "green">edita</span></a> este Departamento!</h1>
{% endif %}



    </div>

{% endblock %}

curso/templates/listDocentes.html
{% extends "layout3.html" %}

{% block content %}


        <div class = "cursoTeste">


<h1 class="titulo2">Docentes</h1>


{% if request.user.is_authenticated %}
    <h1 class="titulo3">Adiciona <a href="https://a22202735.pythonanywhere.com/AppCurso/novoDocente"><span class = "green">aqui</span></a> um docente!</h1>
{% else %}
     <h1 class="titulo3">Adiciona <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppCurso/novoDocente"><span class = "green">aqui</span></a> um docente!</h1>
{% endif %}



    {% for docente in docentes %}
                <div class="article-box1">

                   <div class="info-content">
                       <ul>
                        <h4><a href= "https://a22202735.pythonanywhere.com/AppCurso/docente/{{docente.nome}}">{{docente.nome}}</a></h4>
                       </ul>
                   </div>

                </div>

    {% endfor %}

    </div>



{% endblock %}