BlogApp/urls.py
from django.urls import path
from . import views

app_name = 'artigos'
urlpatterns = [
    path('', views.listArtigos_view, name = 'artigos'),
    path('usuarios', views.listUsuarios_view, name = 'usuarios'),
    path('meusArtigos/', views.listMeusArtigos_view, name = 'meusArtigos'),
    path('usuario/<int:usuario_id>', views.listUsuario_view, name = 'usuario'),
    path('artigo/<str:artigo_name>', views.listArtigo_view, name = 'artigo'),
    path('criarArtigo/novo', views.novo_artigo_view, name = 'novo_artigo'),
    path('criarComentario/novo/<str:artigo_name>' , views.novo_comentario_view, name = 'novo_comentario'),
    path('editarArtigo/<str:artigo_name>', views.edita_artigo_view, name = 'edita_artigo'),
    path('editarComentario/<str:artigo_name>/<int:id>/', views.edita_comentario_view, name = 'edita_comentario'),
    path('editarUsuario', views.edita_usuario_view, name = 'edita_usuario'),
    path('adicionarInfoUsuario', views.novo_InformacaoUser_view, name = 'novo_usuario'),
    path('apagarArtigo/<str:artigo_name>', views.apaga_artigo_view, name = 'apaga_artigo'),
    path('apagarComentario/<str:artigo_name>/<int:id>/', views.apaga_comentario_view, name = 'apaga_comentario'),
    ]

bandas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [path('admin/', admin.site.urls), path('', include('portfolio.urls')), path('noobsite/', include('noobsite.urls')), path('pwsite/', include('pwsite.urls')), path('novaapp/', include('novaapp.urls')), path('AppBandas/', include('bands.urls')), path('BlogApp/', include('BlogApp.urls')),path('AppCurso/',include('curso.urls')),path('AppFestivais/', include('festivais.urls')), path('Autenticacao/', include('Autenticacao.urls')), path('meteo/', include('meteo.urls')), ]

bands/urls.py
from django.urls import path
from . import views

app_name = 'bands'
urlpatterns = [
    path('homePage', views.homePage_view, name = 'homePage'),
    path('', views.listBands_view, name = 'bandas'),
    path('banda/<str:band_name>', views.listAlbums_view, name = 'banda'),
    path('album/<str:album_name>', views.listMusics_view, name = 'album'),
    path('musica/<str:music_name>', views.musica_view, name = 'musica'),
    path('criarBanda/nova', views.nova_banda_view, name = 'nova_banda'),
    path('criarAlbum/novo/<str:band_name>', views.novo_album_view, name = 'novo_album'),
    path('criarMusica/nova/<str:album_name>', views.nova_musica_view, name = 'nova_musica'),
    path('editarBanda/<str:band_name>', views.edita_banda_view, name = 'edita_banda'),
    path('editarAlbum/<str:album_name>', views.edita_album_view, name = 'edita_album'),
    path('editarMusica/<str:musica_name>', views.edita_musica_view, name = 'edita_musica'),
    path('apagarBanda/<str:band_name>', views.apaga_banda_view, name = 'apaga_banda'),
    path('apagarAlbum/<str:album_name>', views.apaga_album_view, name = 'apaga_album'),
    path('apagarMusica/<str:musica_name>', views.apaga_musica_view, name = 'apaga_musica')
    ]

BlogApp/models.py
from django.db import models
from django.contrib.auth.models import User

class infoAdicionalUser(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'infoAdicionalUser')
    imagem = models.ImageField(upload_to='app/fotos', null=True, blank=True)
    biografia = models.TextField(null=True, blank=True)
    dataNascimento = models.DateTimeField(auto_now = False, auto_now_add = False,null=True, blank=True)
    interesses = models.TextField()
    profissao = models.TextField()




class artigos(models.Model):
    autor = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'artigos')
    titulo = models.CharField(max_length = 100)
    corpoDoArtigo = models.CharField(max_length = 1000)
    imagem = models.ImageField(upload_to='app/fotos', null=True, blank=True)
    horaPublicacao = models.DateTimeField(auto_now = False, auto_now_add = False)
    categoria = models.TextField(null = True, blank = True)
    introducao = models.TextField(null = True, blank = True)

    def __str__(self):
        return self.titulo

class comentarioRating(models.Model):
    artigo = models.ForeignKey(artigos, on_delete = models.CASCADE, related_name = 'comentariosRatings')
    autor = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'comentariosRatings')
    comentario = models.CharField(max_length = 1000)
    rating = models.IntegerField()
    horaComentario =  models.DateTimeField(auto_now = False, auto_now_add = False)

BlogApp/forms.py
from django import forms
from .models import  artigos, comentarioRating, infoAdicionalUser


class infoAdicionalUserForm(forms.ModelForm):
    class Meta:
        model = infoAdicionalUser
        fields = ['imagem', 'biografia', 'dataNascimento', 'interesses', 'profissao']

        widgets = {
        'dataNascimento' : forms.DateInput(attrs = {'type':'date'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Recebe o autor como argumento
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user  # Define o autor do artigo
        if commit:
            instance.save()
        return instance




class ArtigoForm(forms.ModelForm):
    class Meta:
        model = artigos
        fields = ['titulo', 'corpoDoArtigo', 'imagem', 'horaPublicacao', 'categoria', 'introducao']

        widgets = {
        'horaPublicacao' : forms.DateInput(attrs = {'type':'date'})
        }

    def __init__(self, *args, **kwargs):
        self.autor = kwargs.pop('autor', None)  # Recebe o autor como argumento
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.autor = self.autor  # Define o autor do artigo
        if commit:
            instance.save()
        return instance


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = comentarioRating
        fields = ['comentario', 'rating', 'horaComentario']

        widgets = {
        'horaComentario' : forms.DateInput(attrs = {'type':'date'})
        }

    def __init__(self, *args, **kwargs):
        self.autor = kwargs.pop('autor', None)
        self.artigo = kwargs.pop('artigo', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.autor = self.autor
        instance.artigo = self.artigo
        if commit:
            instance.save()
        return instance

BlogApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import  ComentarioForm, ArtigoForm, infoAdicionalUserForm
from .models import  artigos, comentarioRating, infoAdicionalUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User



@login_required
def novo_comentario_view(request, artigo_name):
    artigo1 = artigos.objects.get(titulo = artigo_name)
    if request.method == 'POST':
        form = ComentarioForm(request.POST, autor = request.user, artigo = artigo1)
        if form.is_valid():
            form.save()
            return redirect('artigos:artigo', artigo1)
    else:
        form = ComentarioForm(autor = request.user, artigo = artigo1)
    return render(request, 'novoComentario.html', {'form': form})


def novo_InformacaoUser_view(request):
    if request.method == 'POST':
        form = infoAdicionalUserForm(request.POST,request.FILES,  user = request.user)  # Passa o usuário autenticado como autor
        if form.is_valid():
            form.save()
            return redirect('artigos:artigos')  # Redireciona para a página inicial após criar o artigo
    else:
        form = infoAdicionalUserForm(user=request.user)  # Passa o usuário autenticado como autor
    return render(request, 'novoInformacaoUser.html',  {'form': form})




@login_required
def novo_artigo_view(request):
    if request.method == 'POST':
        form = ArtigoForm(request.POST,request.FILES,  autor=request.user)  # Passa o usuário autenticado como autor
        if form.is_valid():
            form.save()
            return redirect('artigos:artigos')  # Redireciona para a página inicial após criar o artigo
    else:
        form = ArtigoForm(autor=request.user)  # Passa o usuário autenticado como autor
    return render(request, 'novoArtigo.html',  {'form': form})


def edita_usuario_view(request):
    info_adicional = infoAdicionalUser.objects.get(user = request.user)
    if request.POST:
        form = infoAdicionalUserForm(request.POST or None, request.FILES, instance=info_adicional,  user=request.user)
        if form.is_valid():
            form.save()
            return redirect('artigos:usuario', request.user.pk)
    else:
        form = infoAdicionalUserForm(instance=info_adicional,  user=request.user)

    context = {'form': form}
    return render(request, 'editaAutor.html', context)





@login_required
def edita_artigo_view(request, artigo_name):
    artigo = artigos.objects.get(titulo = artigo_name)

    if request.POST:
        form = ArtigoForm(request.POST or None, request.FILES, instance=artigo, autor=request.user)
        if form.is_valid():
            form.save()
            return redirect('artigos:artigo', artigo )
    else:
        form = ArtigoForm(instance=artigo, autor=request.user)

    context = {'form': form, 'artigo':artigo}
    return render(request, 'editaArtigo.html', context)

@login_required
def apaga_artigo_view(request, artigo_name):
     artigo = artigos.objects.get(titulo = artigo_name)
     artigo.delete()
     return redirect('artigos:artigos')



@login_required
def edita_comentario_view(request, artigo_name, id):
    comentario = comentarioRating.objects.get(id = id)
    artigo1 = artigos.objects.get(titulo = artigo_name)

    if request.POST:
        form = ComentarioForm(request.POST or None, request.FILES, instance=comentario, artigo=artigo1, autor = request.user)
        if form.is_valid():
            form.save()
            return redirect('artigos:artigo', artigo1)
    else:
        form = ComentarioForm(instance=comentario)

    context = {'form': form, 'comentario':comentario}
    return render(request, 'editaComentario.html', context)

@login_required
def apaga_comentario_view(request, artigo_name, id):
    comentario = comentarioRating.objects.get(id = id)
    artigo = artigos.objects.get(titulo = artigo_name)

    comentario.delete()
    return redirect('artigos:artigo', artigo)



def listArtigo_view(request, artigo_name):
    context = {
        'artigo' : artigos.objects.get(titulo = artigo_name),
        'comentarios' : comentarioRating.objects.filter(artigo__titulo = artigo_name),
    }
    return render(request, 'listArtigo.html', context)

def listArtigos_view(request):
    usuario_autenticado = request.user
    context = {
        'artigos' : artigos.objects.all(),
        'autor' : usuario_autenticado,
    }
    return render(request, 'listArtigos.html', context)

def listMeusArtigos_view(request):
    usuario_autenticado = request.user
    context = {
        'artigos' : artigos.objects.all(),
        'autor' : usuario_autenticado,
    }
    return render(request, 'listMeusArtigos.html', context)


def listUsuarios_view(request):
    users = User.objects.all()
    context = {
        'users' : users
    }
    return render(request, 'listUsuarios.html',context)

def listUsuario_view(request, usuario_id):
    user = get_object_or_404(User, pk=usuario_id)
    context = {
        'user': user
    }
    return render(request, 'listUsuario.html', context)

BlogApp/templates/editaArtigo.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Edita Artigo</h3>

     <form action="{% url 'artigos:edita_artigo' artigo.titulo %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>





{% endblock %}

BlogApp/templates/editaAutor.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Edita Artigo</h3>



     <form action="{% url 'artigos:edita_usuario'  %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>





{% endblock %}

BlogApp/templates/editaComentario.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Edita Artigo</h3>

     <form action="{% url 'artigos:edita_comentario' comentario.artigo.titulo  comentario.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>





{% endblock %}

BlogApp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
 <meta charset = "UTF-8">
 <title>Artigos</title>
</head>
<body>
     <h1>Artigos</h1>

     {% block content %}
     {% endblock %}


</body>
</html>

BlogApp/templates/layout2.html
<!DOCTYPE html>
<html>
<head>
 <meta charset = "UTF-8">
   {% load static %}
   <link rel="stylesheet" href="{% static 'blog/estilos.css' %}">
 <title>Artigos</title>
</head>
<body>



<nav>
  <div class="wrapper">
    <div class="logo"><a href="#">fakebook</a></div>
    <input type="radio" name="slider" id="menu-btn">
    <input type="radio" name="slider" id="close-btn">
    <ul class="nav-links">
      <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
      <li><a href="https://a22202735.pythonanywhere.com/BlogApp/">Artigos</a></li>
      <li><a href="https://a22202735.pythonanywhere.com/BlogApp/usuarios">Usuários</a></li>
      <li>

        {% if request.user.is_authenticated %}
            <a href="#" class="desktop-item">Meu Perfil</a>
            <input type="checkbox" id="showDrop">
            <label for="showDrop" class="mobile-item">Meu Perfil</label>
            <ul class="drop-menu">
            <li><a href="https://a22202735.pythonanywhere.com/BlogApp/usuario/{{request.user.id}}">Perfil</a></li>
            {% for info in request.user.infoAdicionalUser.all %}
                <li><a href="https://a22202735.pythonanywhere.com/BlogApp/editarUsuario">Editar Perfil</a></li>
            {% empty %}
                <li><a href="https://a22202735.pythonanywhere.com/BlogApp/adicionarInfoUsuario">Editar Perfil</a></li>
            {% endfor %}
            <li><a href="https://a22202735.pythonanywhere.com/BlogApp/meusArtigos/">Meus Artigos</a></li>
            <li> <a href="https://a22202735.pythonanywhere.com/Autenticacao/logout/Artigos">Logout</a></li>
            </ul>
            </li>
        {% else %}
       <li> <a href= "https://a22202735.pythonanywhere.com/Autenticacao/login/Artigos">Login</a></li>
        {% endif %}

        <li><a href="#">Contacto</a></li>

    </ul>
    <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
  </div>
</nav>

<div class="body-container">
    <div class="body-text">
{% if request.user.is_authenticated %}

{% else %}
  <div class="title">O <a href="#">Fakebook</a> ajuda-te a comunicar e a partilhar com as pessoas que fazem parte da tua vida.</div>
  <div class="sub-title">Cria uma conta ou inicia sessão no <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/Artigos">Fakebook</a>!</div>
{% endif %}
</div>
</div>

     {% block content %}
     {% endblock %}


</body>
</html>

BlogApp/templates/listArtigo.html
{% extends "layout2.html" %}

{% block content %}
<a href="http://a22202735.pythonanywhere.com/BlogApp/usuario/{{user.id}}">{{artigo.autor}}</a>

        <div class="body-content">
        <div class="column column-other1">
                <div class="article-box3">
                    <div class="autor-text5">
                    <p class="titulo">{{artigo.titulo}}</p>
                    <img src="{{ artigo.imagem.url }}" alt="{{ artigo.titulo }}">
                    <li><span class="blue">Autor: </span><a href="http://a22202735.pythonanywhere.com/BlogApp/usuario/{{user.id}}"><span class="black">{{artigo.autor}}</span></a></li>
                    <li><span class="blue">Hora da Publicação: </span>{{artigo.horaPublicacao}}</li>
                    <li><span class="blue">Categoria: </span>{{artigo.categoria}}</li>
                    <li><span class="blue">Corpo do Artigo: </span>{{artigo.corpoDoArtigo}}</li>
                    <p class="titulo1">Comentários:</p>
                    <div>
                    <p><a href="https://a22202735.pythonanywhere.com/BlogApp/criarComentario/novo/{{artigo.titulo}}"><span class="blue">Clica aqui para adicionar um comentário</span></a></p>
                    </div>
                    {% for comentario in comentarios %}
                    {% for info in comentario.autor.infoAdicionalUser.all %}
                    <div class="autor-text1">
                    <img src="{{ info.imagem.url }}" alt="{{ comentario.autor.first_name }}">
                    <p>{{comentario.autor.username}}</p>
                    </div>
                    {% if request.user == comentario.autor %}
                    <li class="comentario"><p>{{comentario.comentario}} <a href="https://a22202735.pythonanywhere.com/BlogApp/editarComentario/{{artigo.titulo}}/{{comentario.id}}"><span class="blue">(Editar)</span></a> <a href="https://a22202735.pythonanywhere.com/BlogApp/apagarComentario/{{artigo.titulo}}/{{comentario.id}}"><span class="blue">(Apagar)</span></a></p></li>
                    {% else %}
                    <li class="comentario"><p>{{comentario.comentario}}</p></li>
                    {% endif %}
                    <li class="comentario"><p>Rating: {{comentario.rating}}</p></li>
                    <li class="comentario"><p>{{comentario.horaComentario}}</p></li>
                    {% endfor %}
                    {% endfor %}
                </div>
    </div>
    </div>






{% endblock %}

BlogApp/templates/listArtigos.html
{% extends "layout2.html" %}

{% block content %}


  <div class="body-container">
    <div class="body-text">
        {% if request.user.is_authenticated %}
        <div class="title"><a href="#">{{ user.first_name }}</a> em que estás a pensar?</div>
        <div class="sub-title">Escreve algo <a href="https://a22202735.pythonanywhere.com/BlogApp/criarArtigo/novo">aqui</a>!</div>
        {% else %}
        <!-- Caso o usuário não esteja autenticado, alvez queira adicionar algo aqui -->
        {% endif %}
    </div>

    <div class="body-content">
        <div class="column column-sport">
            <div class="text-box">
            <h2>Entretenimento</h2>
            </div>
            {% for artigo in artigos %}
            {% if artigo.categoria == 'Entretenimento' %}
            <div class="article-box">
                <img src="{{ artigo.imagem.url }}" alt="{{ artigo.titulo }}">
                <a href="{% url 'artigos:artigo' artigo.titulo %}" class="left-align">{{ artigo.titulo }}</a>
                <div class="autor-text3">
                <a href="http://a22202735.pythonanywhere.com/BlogApp/usuario/{{user.id}}"><span class="black">{{artigo.autor}}</span></a>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="column column-middle">
            <div class="text-box">
            <h2>Desporto</h2>
            </div>
            {% for artigo in artigos %}
            {% if artigo.categoria == 'Desporto' %}
            <div class="article-box">
                <img src="{{ artigo.imagem.url }}" alt="{{ artigo.titulo }}">
                <a href="{% url 'artigos:artigo' artigo.titulo %}" class="left-align">{{ artigo.titulo }}</a>
                <div class="autor-text3">
                <a href="http://a22202735.pythonanywhere.com/BlogApp/usuario/{{user.id}}"><span class="black">{{artigo.autor}}</span></a>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="column column-other">
            <div class="text-box">
            <h2>Politica</h2>
            </div>
            {% for artigo in artigos %}
            {% if artigo.categoria == 'Politica' %}
            <div class="article-box">
                <img src="{{ artigo.imagem.url }}" alt="{{ artigo.titulo }}">
                <a href="{% url 'artigos:artigo' artigo.titulo %}" class="left-align">{{ artigo.titulo }}</a>
                <div class="autor-text3">
                <a href="http://a22202735.pythonanywhere.com/BlogApp/usuario/{{user.id}}"><span class="black">{{artigo.autor}}</span></a>
                </div>
                <p>{{artigo.introducao}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

BlogApp/templates/listArtigosAutor.html
{% extends "layout2.html" %}

{% block content %}


  <h2><a href= "{% url 'artigos:artigos'  %}">Home Page</a></h2>

    {% if request.user.is_authenticated %}
        <a href="http://a22202735.pythonanywhere.com/Autenticacao/logout/artigos/autor/{{autor.primeiroNome}} {{autor.ultimoNome}}"><button>Logout</button></a>
    {% else %}
        <a href= "http://a22202735.pythonanywhere.com/Autenticacao/login/artigos/autor/{{autor.primeiroNome}} {{autor.ultimoNome}}"><button>Login</button></a>
    {% endif %}

  <h3>{{autor.primeiroNome}} {{autor.ultimoNome}}</h3>


  <p>Descrição: {{autor.descricao}}</p>
  <p>Email: {{autor.email}}</p>
  <p>Idade: {{autor.idade}}</p>
  <img src="{{ autor.fotoPerfil.url }}" width="200" height="150">




  <p>Lista de Artigos:</p>
  {% for artigo in artigos %}
    <ul>
         <li>Artigo: <a href= "{% url 'artigos:artigo' artigo.titulo %}">{{artigo.titulo}}</a></li>
    </ul>
  {% endfor %}


    {% if request.user.is_authenticated %}
      <a href="http://a22202735.pythonanywhere.com/artigos/editarAutor/{{autor.primeiroNome}} {{autor.ultimoNome}}"><button>Editar Informação do Autor</button></a>
    {% else %}
     <a href="http://a22202735.pythonanywhere.com/Autenticacao/login/artigos/editarAutor/{{autor.primeiroNome}} {{autor.ultimoNome}}"><button>Editar Informação do Autor</button></a>
    {% endif %}

    {% if request.user.is_authenticated %}
      <a href="http://a22202735.pythonanywhere.com/artigos/apagarAutor/{{autor.primeiroNome}} {{autor.ultimoNome}}"><button>Apagar Autor</button></a>
    {% else %}
     <a href="http://a22202735.pythonanywhere.com/Autenticacao/login/artigos/apagarAutor/{{autor.primeiroNome}} {{autor.ultimoNome}}"><button>Apagar Autor</button></a>
    {% endif %}


{% endblock %}

BlogApp/templates/listMeusArtigos.html
{% extends "layout2.html" %}

{% block content %}


  <div class="body-container">

    <div class="body-content">
        <div class="column column-other">
            <div class="text-box1">
            <h2>Meus Artigos</h2>
            </div>
            <p><span class="blue">Clique no artigo para editar</span></p>
            {% for artigo in artigos %}
            {% if artigo.autor == autor %}
            <div class="article-box">
                <img src="{{ artigo.imagem.url }}" alt="{{ artigo.titulo }}">
                <a href="https://a22202735.pythonanywhere.com/BlogApp/editarArtigo/{{artigo.titulo}}" class="left-align">{{ artigo.titulo }}</a>
                <div class="autor-text3">
                <p>{{artigo.autor.first_name}} {{artigo.autor.last_name}}</p>
                </div>
                <p>{{artigo.introducao}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

BlogApp/templates/listUsuarios.html
{% extends "layout2.html" %}

{% block content %}


    <div class="body-content">
        <div class="column column-other">
            <div class="text-box1">
            <h2>Usuarios</h2>
            </div>
            {% for user in users %}
            {% if user.username != 'admin' %}
                <div class="article-box1">
                {% for info in user.infoAdicionalUser.all %}
                    <div class="autor-text1">
                    <img src="{{ info.imagem.url }}" alt="{{ user.first_name }}">
                    <p><a href="http://a22202735.pythonanywhere.com/BlogApp/usuario/{{user.id}}"><span class="blue">{{user.first_name}} {{user.last_name}}</span></a></p>
                    </div>
                    <div class="autor-text">
                    <li>Bio: {{ info.biografia}} </li>
                    </div>
                {% empty %}
                    <div class="autor-text1">
                    <p>{{user.first_name}} {{user.last_name}}</p>
                    </div>
                    <p>Este usuario não tem perfil atualizado.</p>
                {% endfor %}
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

BlogApp/templates/novoArtigo.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Novo Artigo</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classe Autor, numa tabela -->
      </table>
      <input type="submit" value="Criar artigo">

    </form>



{% endblock %}

BlogApp/templates/novoAutor.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Novo Autor</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classe Autor, numa tabela -->
      </table>
      <input type="submit" value="Criar autor">

    </form>



{% endblock %}

BlogApp/templates/novoComentario.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Novo Comentário</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->
      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classe Autor, numa tabela -->
      </table>
      <input type="submit" value="Criar comentário">

    </form>



{% endblock %}

BlogApp/templates/novoInformacaoUser.html
{% extends "layout2.html" %}

{% block content %}
     <h3>Nova Info Usuario</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classe Autor, numa tabela -->
      </table>
      <input type="submit" value="Criar Info Usuário">

    </form>



{% endblock %}