bandas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [path('admin/', admin.site.urls), path('', include('portfolio.urls')), path('noobsite/', include('noobsite.urls')), path('pwsite/', include('pwsite.urls')), path('novaapp/', include('novaapp.urls')), path('AppBandas/', include('bands.urls')), path('BlogApp/', include('BlogApp.urls')),path('AppCurso/',include('curso.urls')),path('AppFestivais/', include('festivais.urls')), path('Autenticacao/', include('Autenticacao.urls')), path('meteo/', include('meteo.urls')), ]

bands/urls.py
from django.urls import path
from . import views

app_name = 'bands'
urlpatterns = [
    path('homePage', views.homePage_view, name = 'homePage'),
    path('', views.listBands_view, name = 'bandas'),
    path('banda/<str:band_name>', views.listAlbums_view, name = 'banda'),
    path('album/<str:album_name>', views.listMusics_view, name = 'album'),
    path('musica/<str:music_name>', views.musica_view, name = 'musica'),
    path('criarBanda/nova', views.nova_banda_view, name = 'nova_banda'),
    path('criarAlbum/novo/<str:band_name>', views.novo_album_view, name = 'novo_album'),
    path('criarMusica/nova/<str:album_name>', views.nova_musica_view, name = 'nova_musica'),
    path('editarBanda/<str:band_name>', views.edita_banda_view, name = 'edita_banda'),
    path('editarAlbum/<str:album_name>', views.edita_album_view, name = 'edita_album'),
    path('editarMusica/<str:musica_name>', views.edita_musica_view, name = 'edita_musica'),
    path('apagarBanda/<str:band_name>', views.apaga_banda_view, name = 'apaga_banda'),
    path('apagarAlbum/<str:album_name>', views.apaga_album_view, name = 'apaga_album'),
    path('apagarMusica/<str:musica_name>', views.apaga_musica_view, name = 'apaga_musica')
    ]

bands/models.py
from django.db import models

class Band (models.Model):
    name = models.CharField(max_length = 100)
    country = models.CharField(max_length = 100)
    yearCreated = models.IntegerField()
    biografia = models.TextField(default=' ', null=True, blank=True)
    imagem = models.ImageField(upload_to='app/fotos', null=True, blank=True)

    def __str__(self):
        return self.name



class Album (models.Model):
    name = models.CharField(max_length = 100)
    band  = models.ForeignKey(Band, on_delete = models.CASCADE)
    anoLancamento = models.IntegerField()
    imagemAlbum = models.ImageField(upload_to='app/fotos', null=True, blank=True)

    def __str__(self):
        return self.name


class Music(models.Model):
    url = models.URLField(max_length = 200)
    name = models.CharField(max_length = 100)
    duration = models.CharField(max_length = 10, default = ' ')
    album = models.ForeignKey(Album, on_delete = models.CASCADE, related_name = 'musics')
    letra = models.TextField(default=' ', null=True, blank=True)

    def __str__(self):
        return self.name

bands/forms.py
from django import forms
from .models import Band, Album, Music

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'

class MusicForm(forms.ModelForm):
    class Meta:
        model = Music
        fields = '__all__'

bands/views.py
from django.shortcuts import render ,redirect
from .forms import BandForm, AlbumForm, MusicForm
from .models import Music, Album, Band
from django.contrib.auth.decorators import login_required

@login_required
def nova_banda_view(request):
    form = BandForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('bands:bandas')
    context = {'form': form}

    return render(request, 'novaBanda.html', context)


@login_required
def edita_banda_view(request,  band_name):
    banda = Band.objects.get(name = band_name)

    if request.POST:
        form = BandForm(request.POST or None, request.FILES, instance = banda)
        if form.is_valid():
            form.save()
            return redirect('bands:banda' , banda)
    else:
        form = BandForm(instance = banda)  # cria formulário com dados da instância autor

    context = {'form': form, 'banda':banda}
    return render(request, 'editaBanda.html', context)


@login_required
def apaga_banda_view(request, band_name):
    banda = Band.objects.get(name = band_name)
    banda.delete()
    return redirect('bands:bandas')



@login_required
def novo_album_view(request, band_name):
    banda = Band.objects.get(name = band_name)

    form = AlbumForm(request.POST or None, request.FILES)

    bandaNome = band_name
    if form.is_valid():
        form.save()
        return redirect('bands:banda' , bandaNome)
    context = {'form': form, 'banda' : banda}

    return render(request, 'novoAlbum.html', context)


@login_required
def edita_album_view(request,  album_name):
    album = Album.objects.get(name = album_name)

    if request.POST:
        form = AlbumForm(request.POST or None, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bands:album', album)
    else:
        form = AlbumForm(instance=album)  # cria formulário com dados da instância autor

    context = {'form': form, 'album':album}
    return render(request, 'editaAlbum.html', context)



@login_required
def apaga_album_view(request, album_name):
     album = Album.objects.get(name = album_name)
     album.delete()
     return redirect('bands:banda' , album.band)


@login_required
def nova_musica_view(request, album_name):
    form = MusicForm(request.POST or None, request.FILES)
    album = album_name
    if form.is_valid():
        form.save()
        return redirect('bands:album', album)
    context = {'form': form}

    return render(request, 'novaMusica.html',context)


@login_required
def edita_musica_view(request,  musica_name):
    musica = Music.objects.get(name = musica_name)

    if request.POST:
        form = MusicForm(request.POST or None, request.FILES, instance=musica)
        if form.is_valid():
            form.save()
            return redirect('bands:musica', musica)
    else:
        form = MusicForm(instance=musica)  # cria formulário com dados da instância autor

    context = {'form': form, 'musica':musica}
    return render(request, 'editaMusica.html', context)


@login_required
def apaga_musica_view(request, musica_name):
    musica = Music.objects.get(name = musica_name)
    musica.delete()
    return redirect('bands:album', musica.album )


def musica_view(request, music_name):
    context = {
        'music' : Music.objects.get(name = music_name),
    }
    return render(request, 'music.html', context)


def listMusics_view(request, album_name):
    context = {
        'musics' : Music.objects.filter(album__name = album_name),
        'album' : Album.objects.get(name = album_name),
    }
    return render(request, 'album.html', context)


def listAlbums_view(request, band_name):
    context = {
        'albuns' : Album.objects.filter(band__name = band_name),
        'band' : Band.objects.get(name = band_name),
    }
    return render(request, 'band.html', context)

def homePage_view(request):
    context = {}
    return render(request, 'homePage.html',context)

def listBands_view(request):
    context = {
        'bands' : Band.objects.all(),
    }
    return render(request, 'listBands.html', context)

bands/templates/album.html
{% extends "layout.html" %}

{% block content %}

    {% if request.user.is_authenticated %}
        <a class ="teste" href="https://a22202735.pythonanywhere.com/Autenticacao/logout/AppBandas/album/{{album.name}}"><button  class="button-22" role="button" >Logout</button></a>
    {% else %}
        <a class ="teste" href= "https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/album/{{album.name}}"><button  class="button-22" role="button" >Login</button></a>
    {% endif %}


    <h1>{{album.name}}</h1>

     <div class="info-box">
            <div class="info-content">
            <ul>
                <p>Banda: {{album.band.name}} </p>
                <p>Ano Criação: {{album.anoLancamento}}</p>
            </ul>

            <div class = "info-editarEapagar">
            {% if request.user.is_authenticated %}
      <a  class ="teste"  href="https://a22202735.pythonanywhere.com/AppBandas/editarAlbum/{{album.name}}">Editar informação do Album</a>
{% else %}
     <a  class ="teste"  href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/editarAlbum/{{album.name}}">Editar Informação do Album</a>
{% endif %}
</div>

<div class = "info-editarEapagar">
{% if request.user.is_authenticated %}
     <a class ="teste"   href="https://a22202735.pythonanywhere.com/AppBandas/apagarAlbum/{{album.name}}">Apagar Album</a>
{% else %}
     <a class ="teste"   href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/apagarAlbum/{{album.name}}">Apagar Album</a>
{% endif %}
</div>

        </div>
        <div class="info-image">
            <img class="info-image" src="{{ album.imagemAlbum.url }}">
        </div>
 </div>


<div class="info-box">
            <div class="info-content">
                  <ul>
  <p>Lista de Musicas do Album:</p>
  {% for music in musics %}
    <ul>
        <div class = "info-editarEapagar">
        <li><a href="{% url 'bands:musica' music.name %}">{{music.name}}</a></li>
        </div>
    </ul>
    {% endfor %}
      <ul>

<div class = "info-editarEapagar">
{% if request.user.is_authenticated %}
     <a  class ="teste" href="{% url 'bands:nova_musica' album.name %}">Inserir nova Musica!</a>
{% else %}
     <a  class ="teste" href="https://a22202735.pythonanywhere.com/Autenticacao/login/bandas/criarMusica/nova/{{album.name}}">Inserir nova Musica!</a>
{% endif %}
</div>



        </div>
 </div>






{% endblock %}

bands/templates/band.html
{% extends "layout.html" %}

{% block content %}



    {% if request.user.is_authenticated %}
        <a class ="teste" href="https://a22202735.pythonanywhere.com/Autenticacao/logout/AppBandas/banda/{{band.name}}"><button  class="button-22" role="button" >Logout</button></a>
    {% else %}
        <a class = "teste" href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/banda/{{band.name}}"><button  class="button-22" role="button">Login</button></a>
    {% endif %}

  <h1>{{band.name}}</h1>

        <div class="info-box">
            <div class="info-content">
            <ul>
               <p>Biografia: {{band.biografia}}</p>
               <p>Pais: {{band.country}}</p>
               <p>Ano Criação: {{band.yearCreated}}</p>
            </ul>

            <div class = "info-editarEapagar">
            {% if request.user.is_authenticated %}
     <a class ="teste" href="https://a22202735.pythonanywhere.com/AppBandas/editarBanda/{{band.name}}">Editar informação da Banda!</a>
{% else %}
     <a class ="teste" href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/editarBanda/{{band.name}}">Editar Informação da Banda!</a>
{% endif %}
</div>

<div class = "info-editarEapagar">
{% if request.user.is_authenticated %}
     <a class = "teste" href="{% url 'bands:apaga_banda' band.name %}">Apagar Banda!</a>
{% else %}
     <a  class = "teste" href="https://a22202735.pythonanywhere.com/Autenticacao/login/banda/{{band.name}}">Apagar Banda!</a>
{% endif %}
</div>
        </div>
        <div class="info-image">
            <img class="info-image" src="{{ band.imagem.url }}">
        </div>

        </div>


        <div class="info-box">
            <div class="info-content">
            <ul>
               <p>Lista de Albuns da Banda:</p>
                {% for album in albuns %}
                 <div class = "info-editarEapagar">
                    <li><a href="{% url 'bands:album' album.name %}">{{album.name}}</a></li>
                 </div>
                {% endfor %}
                </ul>

            <div class = "info-editarEapagar">
            {% if request.user.is_authenticated %}
             <a href="{% url 'bands:novo_album' band.name %}">Inserir novo Album!</a>
            {% else %}
            <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/criarAlbum/novo/{{band.name}}">Inserir novo Album!</a>
            {% endif %}
            </div>



            </div>
        </div>














{% endblock %}

bands/templates/editaAlbum.html
{% extends "layout.html" %}

{% block content %}
    <h3>Edita Album</h3>

    <form action="{% url 'bands:edita_album' album.name %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bands/templates/editaBanda.html
{% extends "layout.html" %}

{% block content %}
    <h3>Edita Banda</h3>

    <form action="{% url 'bands:edita_banda' banda.name %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bands/templates/editaMusica.html
{% extends "layout.html" %}

{% block content %}
    <h3>Edita Musica</h3>

    <form action="{% url 'bands:edita_musica' musica.name %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bands/templates/homePage.html
{% extends "layout.html" %}

{% block content %}



  	<div class="section-center">
  		<h1 class="mb-0">Rock Hub</h1>
  		<h2 >by vasco pereira</h2>
  	</div>



{% endblock %}

bands/templates/layout.html
<!DOCTYPE html>
<html>
<head>
   <meta charset = "UTF-8">
   {% load static %}
   <link rel="stylesheet" href="{% static 'bandas/estilos.css' %}">
   <title>Bandas</title>
</head>
<body>

    <input class="menu-icon" type="checkbox" id="menu-icon" name="menu-icon"/>
  	<label for="menu-icon"></label>
  	<nav class="nav">
  		<ul class="pt-5">
  		    <li><a href="https://a22202735.pythonanywhere.com/AppBandas/homePage">Home Page</a></li>
  			<li><a href="https://a22202735.pythonanywhere.com/AppBandas/">Bandas</a></li>
  			<li><a href="https://a22202735.pythonanywhere.com/Autenticacao/login/Bandas">Login</a></li>
  			<li><a href="https://a22202735.pythonanywhere.com/Autenticacao/logout/Bandas">Logout</a></li>
  			<li><a href="https://www.instagram.com/vasc0_pereira/">Contacto</a></li>
  		</ul>
  	</nav>

     {% block content %}
     {% endblock %}
</body>
</html>

bands/templates/listBands.html
{% extends "layout.html" %}

{% block content %}

    {% if request.user.is_authenticated %}
        <a class ="teste" href="https://a22202735.pythonanywhere.com/Autenticacao/logout/Bandas"><button  class="button-22" role="button" >Logout</button></a>
    {% else %}
        <a class = "teste" href="https://a22202735.pythonanywhere.com/Autenticacao/login/Bandas"><button  class="button-22" role="button">Login</button></a>
    {% endif %}

     <h1>Lista de Bandas: </h1>
    {% for banda in bands %}

        <div class="info-box">
            <div class="info-content">
            <ul>
                <a href="{% url 'bands:banda' banda.name %}">{{banda.name}}</a>
               <p>{{banda.biografia}}</p>


            </ul>
        </div>
        <div class="info-image">
            <img class="info-image" src="{{ banda.imagem.url }}">
        </div>
        </div>

    {% endfor %}


<div>
{% if request.user.is_authenticated %}
    <a  class ="teste" href="{% url 'bands:nova_banda' %}"><button class="button-22" role="button">Inserir nova Banda</button></a>
{% else %}
     <a class ="teste" href="https://a22202735.pythonanywhere.com/Autenticacao/login/bandas/criarBanda/nova"><button class="button-22" role="button">Inserir nova Banda</button></a>
{% endif %}
</div>

{% endblock %}

bands/templates/music.html
{% extends "layout.html" %}

{% block content %}



    {% if request.user.is_authenticated %}
        <a class = "teste"href="https://a22202735.pythonanywhere.com/Autenticacao/logout/AppBandas/musica/{{music.name}}"><button  class="button-22" role="button" >Logout</button></a>
    {% else %}
        <a class = "teste" href= "https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/musica/{{music.name}}"><button  class="button-22" role="button">Login</button></a>
    {% endif %}

<h1>{{music.name}}</h1>

<div class="info-box">
    <div class="info-content">

  <p>Url: <a href= "{{music.url}}"> {{music.url}}</a></p>
  <p>Duração: {{music.duration}}</p>
  <p>Album: <a href= "{% url 'bands:album' music.album.name %}">{{music.album.name}}</a></p>
  <pre>Letra: {{music.letra}}</pre>

<div class = "info-editarEapagar">
{% if request.user.is_authenticated %}
      <a href="{% url 'bands:edita_musica' music.name %}">Editar informação da Música!</a>
{% else %}
     <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/editarMusica/{{music.name}}">Editar Informação da Música!</a>
{% endif %}
</div>

<div class = "info-editarEapagar">
{% if request.user.is_authenticated %}
     <a href="{% url 'bands:apaga_musica' music.name %}">Apagar Música!</a>
{% else %}
     <a href="https://a22202735.pythonanywhere.com/Autenticacao/login/AppBandas/album/{{music.album.name}}">Apagar Música!</a>
{% endif %}
</div>


</div>
</div>







{% endblock %}

bands/templates/novaBanda.html
{% extends "layout.html" %}

{% block content %}
    <h3>Nova Banda</h3>

     <form action="" method="post" enctype='multipart/form-data'>

          {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar Banda">

    </form>


{% endblock %}

bands/templates/novaMusica.html
{% extends "layout.html" %}

{% block content %}
    <h3>Nova Musica</h3>

     <form action="" method="post" enctype='multipart/form-data'>

          {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar Musica">

    </form>


{% endblock %}

bands/templates/novoAlbum.html
{% extends "layout.html" %}

{% block content %}
    <h3>Novo Album</h3>

     <form action="" method="post" enctype='multipart/form-data'>

          {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar Album">

    </form>


{% endblock %}